"""empty message

Revision ID: a6889e26a94c
Revises: 4aad4f7b688b
Create Date: 2021-03-05 19:41:24.581276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6889e26a94c'
down_revision = '4aad4f7b688b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardio', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardio', 'date')
    # ### end Alembic commands ###
